### ISSUE TITLE
Output in JSON

### ISSUE THREAD

**Issue by miyao-yusuke** [mynlp/jigg#14]
The current system outputs the analysis results in XML, but in many cases a simpler format like JSON is more user-friendly.  I'd like to have an option to change the output format to JSON.

**Comment by kyoshinaga** [comment]
Sorry to ask an elementary question as below.
In the current revision, I can't find jigg.util packages under the src/main directory.
(Under the directory, there are only three directories; ml, nlp, and pipeline.)
However, the main class of jigg, pipeline/Pipeline.scala, is still importing that package.
Even though it is such a situation, the jigg is successfully compiled using "sbt assembly".
What is the main source of jigg.util?

**Comment by hiroshinoji** [comment]
For some reasons, I have temporarily moved some core components in Jigg into another repository, jigg-base. However, after some discussion, we decided to move them back to the core part of the jigg.

Now, in the develop branch, you can find the util directory. Sorry for this inconvenience. Note that in the current setting of build.sbt, the assembled jar does not contain the berkeley parser, so some commands in README cannot be reproduced. (Stanford CoreNLP is included, so should work).

**Comment by kyoshinaga** [comment]
Thank you very much for your treatment.
I can find the util directory under the src/main directory. And I understand the current status of assembled jar. Then I'll try to run it with Stanford CoreNLP.

**Comment by kyoshinaga** [comment]
Currently I use "develop" branch to implement my object which supports JSON output converted from XML.
First of all, I checked whether sbt-assemly command succeeds or not without implementation of my object.
As that result, sbt-assembly didn't finish with following error messages.

```
[info] Including from cache: kuromoji-unidic-0.9.0.jar
[warn] Merging 'license_xml-apis-1.3.03/LICENSE' with strategy 'rename'
[trace] Stack trace suppressed: run last *:assembly for the full output.
[error] (*:assembly) deduplicate: different file contents found in the following:
[error] jigg/pipeline/RequirementSet$$anon$2.class
[error] /home/ubuntu/.ivy2/cache/com.github.mynlp/jigg-base/jars/jigg-base-0.6.jar:jigg/pipeline/RequirementSet$$anon$2.class
[error] Total time: 3 s, completed Apr 25, 2016 7:07:29 AM
```

I tried adding mergeStrategy value to build.sbt. (Ref. https://github.com/sbt/sbt-assembly/tree/0.9.2). However the situation was still same.
How can I resolve or escape this error?

**Comment by hiroshinoji** [comment]
Sorry build.sbt in the latest develop branch seems broken.

I pushed the fixed file. If the problem remains, maybe `clean` command is necessary before `assembly` in `sbt`.

**Comment by kyoshinaga** [comment]
Thank you for your rapid reply.

I pull the fixed file from mynlp/jigg.git, and `clean` and `assemble` commands successfully finished!
Thank you so much!

**Comment by kyoshinaga** [comment]
Sorry, I have one question.

In the fixed build.sbt, the annotatorLibrary map is empty.
I want to use a stanford-corenlp, so then I modified it as follows,

```
val annotatorLibrary = Map(
"corenlp" -> ("com.github.mynlp" % "jigg-stanford-corenlp" % "0.1-SNAPSHOT" % 
"jigg.pipeline.StanfordCoreNLPAnnotator")
)
```

However, I can't succeed `assembly` command.
Does it mean the stanford-corenlp is currently unavailable?

**Comment by hiroshinoji** [comment]
The situation was a bit complex... In the latest version corenlp and kuromoji are already included into jigg, but I forgot to give the paths to them. I now pushed the revised develop to be able to call corenlp directly.

**Comment by kyoshinaga** [comment]
Thank you for your response.

After pulling it, `assembly` command succeeded, and I can use `corenlp[tokenize, ssplit]`!

```
$java -cp target/jigg-assembly-0.6.jar jigg.pipeline.Pipeline -annotators "corenlp[tokenize, ssplit]" 
```

Thank you so much!

**Comment by hiroshinoji** [comment]
Now JSON components seem to work with no problems.
