### ISSUE TITLE
Japanese ccg model is not available.

### ISSUE THREAD

**Issue by rikka** [mynlp/jigg#40]
Hi, I tried to use this software library for japanese ccg.
But the script "download_ccg_model.sh" won't work correctly.
It always shows "403 Forbidden" to me. 

Is this software only for internal use?

**Comment by hiroshinoji** [comment]
Sorry for the inconvenience. In the current release, the CCG parser model is temporary unavailable... I'm now preparing the release of new version (maybe in this week) and the model will be then distributed correctly.

**Comment by hiroshinoji** [comment]
The new version 0.6.1 was released along with the updated CCG parser model.
Now the model file can be downloaded by:

``` sh
$ ./script/download_models.sh
```

Then, the parser can be used with e.g.,

``` sh
$ java -cp "*" jigg.pipeline.Pipeline `-annotators ssplit,kuromoji,jaccg`
```

which performs morphological analysis with kuromoji. The sentence splitting behavior can be customized; see `-help ssplit` for details. In default, it segments in each newline (`\n`) or period (`。`). If the input file is already sentence segmented (i.e., each line corresponds to a sentence), `-ssplit.method newLine` is a better choice.

**Comment by rikka** [comment]
Okay. I confirmed the link is available.
Thanks.
