### ISSUE TITLE
Support Chinese processing

### ISSUE THREAD

**Issue by hiroshinoji** [mynlp/jigg#43]
Stanford CoreNLP supports Chinese processing. Some problems may or may not occur in jigg's CoreNLP's wrapper. Some tests are needed first.

**Comment by fyamamoto10** [comment]
I executed the following command:
```
java -Xmx5g -cp "jar/*" jigg.pipeline.Pipeline -annotators corenlp[tokenize,ssplit,pos] -props StanfordCoreNLP-chinese.properties -file chinese.txt
```

I got the following error.
```
Exception in thread "main" java.io.FileNotFoundException: StanfordCoreNLP-chinese.properties (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at jigg.util.IOUtil$.inStream(IOUtil.scala:45)
        at jigg.util.IOUtil$.openIn(IOUtil.scala:37)
        at jigg.util.ArgumentsParser$.parseRecur(ArgumentsParser.scala:31)
        at jigg.util.ArgumentsParser$.parse(ArgumentsParser.scala:22)
        at jigg.pipeline.Pipeline$.main(Pipeline.scala:407)
        at jigg.pipeline.Pipeline.main(Pipeline.scala)
```

I installed the Stanford CoreNLP Chinese model file from https://stanfordnlp.github.io/CoreNLP/download.html and moved it in the `jar` directory.
I referred to the page https://stanfordnlp.github.io/CoreNLP/human-languages.html to excete the processing of Chinese. I tried the command of this page and It succeeded.

**Comment by hiroshinoji** [comment]
Thanks for testing.
`-props StanfordCoreNLP-chinese.properties` means Jigg tries to read `StanfordCoreNLP-chinese.properties` on the current path, and the error says there is no such file.

You may have to put the property file (maybe on the directory of corenlp) to the Jigg directory, or put elsewhere and point to that path as `-props path/StanfordCoreNLP-chinese.properties`.

But this would not be sufficient. Each line of a property file looks like `xxx=yyy`, and they are passed as the options of Jigg. That is, each `xxx=yyy` is equivalent to give `-xxx yyy` as an option of Jigg (as a command-line option). The problem is to correctly pass the arguments to CoreNLP in Jigg, each option must be formed as `corenlp.xxx=yyy`. For example, if there is `language=chinese` line in the property file, we have to create a new property line, which instead has `corenlp.language=chinese` property.

Could you prepare such customized properties file (putting `corenlp` prefix on every option) and see what's happing when reading it on Jigg?

**Comment by fyamamoto10** [comment]
Thank you for your reply.

I tried to customize the property file (add `corenlp.` prefix) and run with the option `-props`. 
```
java -Xmx5g -cp "jar/*" jigg.pipeline.Pipeline -annotators corenlp[tokenize,ssplit,pos] -props jar/StanfordCoreNLP-chinese-jigg.properties -file chinese.txt
```
This was succesfull. But, the annotations are preferentially used in the property file. It seems the command line `-annotators corenlp[tokenize,ssplit,pos]` is ignored.

Next, I tried to run with the option `-corenlp.props`. 
```
java -Xmx5g -cp "jar/*" jigg.pipeline.Pipeline -annotators corenlp[tokenize,ssplit,pos] -corenlp.props jar/StanfordCoreNLP-chinese-jigg.properties -file chinese.txt
```

The run did not happen the error, but the chinese model files were not loaded. This means that the processing of chinese is not done. The following is the message when executed with `-corenlp.props` option.
```
Annotating chinese.txt with corenlp[tokenize,ssplit,pos] {
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.1 sec].
  corenlp:  [0.2 sec]
} [1.6 sec]
Writing to chinese.txt.xml... done [0.1 sec]
```

**Comment by hiroshinoji** [comment]
Maybe I have to fix CoreNLPAnnotator so that the second command
`-annotators corenlp[tokenize,ssplit,pos] -corenlp.props jar/StanfordCoreNLP-chinese-jigg.properties` works correctly. Other criteria may include:
1. When `-corenlp.props` contains `annotators` attribute, that value would be ignored. Annotators are only specified by the top `-annotators` attribute of Jigg.
2. Jigg will find the property file (`StanfordCoreNLP-chinese.properties`) on the current class path of java resources, as in CoreNLP.
3. Jigg options for corenlp (`-corenlp.xxx.yyy`) will overwrite the default option given by `-corenlp.props`. The latter is assumed to be load from the class path, and that should work as a default to the all settings.

**Comment by hiroshinoji** [comment]
@fyamamoto10 I implemented an easy fix to support Chinese on the `fix-corenlp-chinese` branch. Could you try several commands, and if it's ok, could you add CI tests on this branch? Now by `-corenlp.props StanfordCoreNLP-chinese.properties` Jigg will read the property file on the Chinese jar file of corenlp. No special file for Jigg would be necessary.
