### ISSUE TITLE
nThreads option in pipeline server

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#54]
Does the server command currently support `nThreads`?

**Comment by hiroshinoji** [comment]
Yes, the server can process the inputs in parallel. Also the server is implemented in thread-safe meaning that two requests at the same time will be handled sequentially (not concurrently as the server only has one instance of a pipeline).

**Comment by hiroshinoji** [comment]
Now Server contains a bug in `nThreads`. Details are in #61.

**Comment by hiroshinoji** [comment]
Fixed in the latest develop. See #61.
