### ISSUE TITLE
JSON/XML Schema

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#55]
We probably need documentation that defines the schema for output from each of the annotators.
Couldn't find anything in the repo. Where would you suggest I start?

**Comment by JSB97** [comment]
Whoops
https://github.com/mynlp/jigg/wiki/Attributes

**Comment by hiroshinoji** [comment]
That is incomplete and I was planning to integrate them to the page below, which is more informative but not complete.
https://github.com/mynlp/jigg/wiki/Definition-of-Requirement

I can spare some time now so will add more documentation including the guideline to implement new annotator soon.
