### ISSUE TITLE
Handling Special Characters

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#57]
The majority of documents include special characters such as quotes ("), or carriage returns.
My documents employ "\n" to handle carriage returns, and I escape the leading \ with another \, as below.
```
"1. 対処すべき課題\\nこれは桃だ。"
```
Currently JIGG would process all of this as one sentence, and includes the character sequence "\\n", even though the document can be split into two, and that `これは桃だ。` is a sentence.

My work around to this is to replace the above with the below; that is, to introduce a sentence termination character. With Japanese, the "。" is unambiguous, so this solution would probably be reasonable, but I cannot be sure for the "." character in the case of English.
```
"1. 対処すべき課題。これは桃だ。"
```
Are there any 'better' methods for handling such special characters?

**Comment by hiroshinoji** [comment]
As described below, the behavior of Jigg's sentence splitter (or document segmenter) can be customized to some extent.

I think however the current issue is mainly caused by the escaping mechanism of the interface you use (I assume it is `curl`). I found that by `--data-urlencode '"1. 対処すべき課題\\nこれは桃だ。"'`, curl (seems to) automatically escape each `\` so maybe the actual input would become `'"1. 対処すべき課題\\\\nこれは桃だ。"'`. One solution I found to send the newline character is use pipe instead:

```
echo "1. 対処すべき課題\nこれは桃だ。" | curl --data-urlencode @- --data-urlencode "annotators=..."
```

By this, the output would be

```xml
<root>
  <document id="d1">
    <sentences>
      <sentence characterOffsetEnd="14" characterOffsetBegin="0" id="s3">&quot;1. 対処すべき課題\\n</sentence>
      <sentence characterOffsetEnd="20" characterOffsetBegin="14" id="s4">これは桃だ。</sentence>
      <sentence characterOffsetEnd="21" characterOffsetBegin="20" id="s5">&quot;</sentence>
    </sentences>
  </document>
</root>
```

One issue I found when debugging is that the Jigg's JSON output does not follow the standard of escaping mechanism, which I documented in #56 (I will fix it immediately).

A genius sentence splitter for Japanese is still an unsolved problem (#44). As you mentioned, the quotations, and also named entities containing 。 complicate the issue (e.g., モーニング娘。).

Though far from perfect, the sentence splitter currently implemented in Jigg can be customized by setting the regular expression for splitting points. See `-hep ssplit` for the customizable options. In default, it is `\n+|。\n*`, that is, newlines or 。. If you want to segment after `"` in case of `。"`, maybe the following options achieve this:

```
--data-urlencode "annotators=ssplit" --data-urlencode "ssplit.pattern=\n+|。\"\s*|。\s*"
```

For English, the splitter of Stanford CoreNLP is customized in many ways (http://stanfordnlp.github.io/CoreNLP/ssplit.html). See `-help corenlp` for how to modify corenlp options in Jigg.

**Comment by JSB97** [comment]
I think the better option would be to make use of the `--data-binary` option in `curl`, as discussed [here](http://stackoverflow.com/questions/3872427/how-to-send-line-break-with-curl).

As discussed on [this thread](https://github.com/mynlp/jigg/issues/50), one issue I have come across with `echo` is the maximum buffer limit, which will prevent large text from being posted to the server.

**Comment by hiroshinoji** [comment]
Does `\n` work with `--data-binary`in your environment? It doesn't for me (Mac) but `%0A` in `--data` suggested above is working.

**Comment by JSB97** [comment]
Neither work unfortunately - can i ask what version of MacOSX (10.11.12), and curl you are using?
Starngely, according to `man curl`, `--data-binary` does seem the right way to go though.

```
$ curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
````

**Comment by hiroshinoji** [comment]
For me, querying Japanese sentences with `--data` or `--data-binary` does not work for some reason (language setting?). Only `--data-urlencode` accepts Japanese. Is it the same?

`%0A` works in my environment for ascii inputs. Example:
```
$ curl --data-urlencode "annotators=ssplit" --data 'q=aaa%0Abbb' "http://localhost:8080/annotate?outputFormat=json"
{
  ".tag" : "root",
  ".child" : [ {
    ".tag" : "document",
    "id" : "d2",
    ".child" : [ {
      ".tag" : "sentences",
      ".child" : [ {
        ".tag" : "sentence",
        "text" : "aaa",
        "id" : "s3",
        "characterOffsetBegin" : "0",
        "characterOffsetEnd" : "3"
      }, {
        ".tag" : "sentence",
        "text" : "bbb",
        "id" : "s4",
        "characterOffsetBegin" : "4",
        "characterOffsetEnd" : "7"
      } ]
    } ]
  } ]
}
```

I used the same version of `curl` as you on zsh 5.0.8 and OSX (10.11.6).

**Comment by hiroshinoji** [comment]
Though it may not be ideal, one can send a larger text using `--data-urlencode @filename` if the input text is on a file. In what situation is it necessary to give such larger input string directly to curl?

**Comment by JSB97** [comment]
To your first point - restricting attention to Japanese and the choice of `data`,`data-binary`, and `data-urlencode`.
I get the same result - only `data-urlencode` returns a parse for JP.
```
# ERROR - The requested resource could not be found.
curl --data-urlencode "annotators=ssplit" --data 'q=あい' "http://localhost:8080/annotate?outputFormat=json"

# ERROR - The requested resource could not be found.
curl --data-urlencode "annotators=ssplit" --data-binary 'q=あい' "http://localhost:8080/annotate?outputFormat=json"

# PARSED
curl --data-urlencode "annotators=ssplit" --data-urlencode 'q=あい' "http://localhost:8080/annotate?outputFormat=json"
```

These results suggest that for Jigg server to parse Japanese, any text needs to be encoded. 
That is 'あい' must be encoded to '%E3%81%82%E3%81%84'. (you can test this [here](https://www.w3schools.com/tags/ref_urlencode.asp) - use the form)

Fortunately for us `--data-urlencode` handles this.


Unfortunately, if we use `--data-urlencode` to parse `あ%0Aい`, for the `%0A` character, we are actually passing `%250A`, which removes the line feed entirely! This is true, irrespective of language.

```
# PARSED BUT NOT SPLIT AT '%0A'
# EN
curl --data-urlencode "annotators=ssplit" --data-urlencode 'q=aaa%0Abbb' "http://localhost:8080/annotate?outputFormat=json"
# JP
curl --data-urlencode "annotators=ssplit" --data-urlencode 'q=あ%0Aい' "http://localhost:8080/annotate?outputFormat=json"
```


To make things slightly confusing, Jigg itself recognises  [`line feed`](https://www.w3schools.com/tags/ref_urlencode.asp) as '%0A'.
This is the reason why the below split works. When we pass `aaa%0Abbb`, with the `--data` option, the characters '%0A' are passed, but not in the encoded form.
```
# PARSED AND SPLIT AT '%0A'
# EN
curl --data-urlencode "annotators=ssplit" --data 'q=aaa%0Abbb' "http://localhost:8080/annotate?outputFormat=json"
```

The solution we need therefore is either;

1. Use `--data-urlencode` and at the same time include a carriage return in the string that is not '%0A'.
2. Encode all characters and use the `--data` option.

For `1`, need to do a bit more digging, but `2` looks good - Jigg even returns all characters decoded :)

```
# PARSED AND SPLIT AT '%0A'
# EN
curl --data-urlencode "annotators=ssplit" --data 'q=aaa%0Abbb' "http://localhost:8080/annotate?outputFormat=json"
# JP
curl --data-urlencode "annotators=ssplit" --data 'q=%E3%81%82%0A%E3%81%84' "http://localhost:8080/annotate?outputFormat=json"
```

**Comment by hiroshinoji** [comment]
I see. The behavior is the same in my environment. If it is allowed, yes, encoding all characters in preprocessing seems to be a reasonable solution.

Regarding 1, I think it is similar to my suggestion above to pass the content in another file by `--data-urlencode @file`. I found in this case, `--data-urlencode q=@file` does not work (`q=@file` is regarded as an input string); however, by `--data-urlencode @file`, all contents in the file are send as an input text including `=` and hence `q=` is unnecessary.

**Comment by JSB97** [comment]
Revisting this again. Your proposed use of `split.pattern` wasn't quite right. You proposed `--data-urlencode "ssplit.pattern=\n+|。\"\s*|。\s*"`, but this since `curl` escapes each `\`, we need to use `--data-urlencode "ssplit.pattern=\\\\n+|。\"\s*|。\s*"` instead.

```
# 1. Sentence is not split.
echo "1. 対処すべき課題\\nこれは桃だ。" | curl "http://localhost:8080/annotate?outputFormat=json" --data-urlencode @- --data-urlencode "annotators=ssplit" --data-urlencode "ssplit.pattern=\n+|。\"\s*|。\s*"

# 2. Sentence split correctly.
echo "1. 対処すべき課題\\nこれは桃だ。" | curl "http://localhost:8080/annotate?outputFormat=json" --data-urlencode @- --data-urlencode "annotators=ssplit" --data-urlencode "ssplit.pattern=\\\\n+|。\"\s*|。\s*"
```
The second command leaves `\\n` at the end of the first sentence, but presumably that can be handled with post-processing...

**Comment by JSB97** [comment]
Revisting this again. Your proposed use of `split.pattern` wasn't quite right. You proposed `--data-urlencode "ssplit.pattern=\n+|。\"\s*|。\s*"`, but this since `curl` escapes each `\`, we need to use `--data-urlencode "ssplit.pattern=\\\\n+|。\"\s*|。\s*"` instead.

```
# 1. Sentence is not split.
echo "1. 対処すべき課題\\nこれは桃だ。" | curl "http://localhost:8080/annotate?outputFormat=json" --data-urlencode @- --data-urlencode "annotators=ssplit" --data-urlencode "ssplit.pattern=\n+|。\"\s*|。\s*"

# 2. Sentence split correctly.
echo "1. 対処すべき課題\\nこれは桃だ。" | curl "http://localhost:8080/annotate?outputFormat=json" --data-urlencode @- --data-urlencode "annotators=ssplit" --data-urlencode "ssplit.pattern=\\\\n+|。\"\s*|。\s*"
```
The second command returns the desired split, but leaves `\\n` at the end of the first sentence.

**Comment by hiroshinoji** [comment]
In my environment, I found that `zsh` can correctly handle the "unescaped" input `1. 対処すべき課題\nこれは桃だ。`, while on `bash`, it automatically escapes `\n` and causes the problem above.

I mean the problem is due to bash's escaping mechanism, and this can be solved using $''-escaping:

```
echo $"'1. 対処すべき課題\nこれは桃だ。"' | curl "http://localhost:8080/annotate?outputFormat=json" --data-urlencode @- --data-urlencode "annotators=ssplit" --data-urlencode "ssplit.pattern=\n+|。\"\s*|。\s*"
```

This works for me on bash.

**Comment by hiroshinoji** [comment]
I think this was solved.
