### ISSUE TITLE
JSON output does not follow the standard in character escaping

### ISSUE THREAD

**Issue by hiroshinoji** [mynlp/jigg#58]
For example, the standard in JSON to escape `"` is to use `\"`.

Currently all escaping mechanisms are the same as XML, so `&quot;` is outputted in this case, which is bad.

Reference: http://stackoverflow.com/questions/19176024/how-to-escape-special-characters-in-building-a-json-string

**Comment by kyoshinaga** [comment]
Thanks for your posting issue. I modified a method to support the standard in character escaping.

For instance:
- Input text:
``` 
"Hello, world" 
```
- XML output:
```xml 
<root>
  <document id="d0">
    <sentences>
      <sentence id="s0" characterOffsetBegin="0" characterOffsetEnd="15">&quot;Hello, world.&quot;</sentence>
    </sentences>
  </document>
</root>
```
- Json output:
```json
{
  ".tag" : "root",
  ".child" : [ {
    ".tag" : "document",
    "id" : "d0",
    ".child" : [ {
      ".tag" : "sentences",
      ".child" : [ {
        ".tag" : "sentence",
        "text" : "\"Hello, world.\"",
        "id" : "s0",
        "characterOffsetBegin" : "0",
        "characterOffsetEnd" : "15"
      } ]
    } ]
  } ]
}
```

**Comment by hiroshinoji** [comment]
Great. Thank you for your quick action!

**Comment by hiroshinoji** [comment]
@tomeken-yoshinaga 
I noticed that when the original xml contains some characters (e.g., `\n`), `JSONUtil.toJSONFromNode` fails with the following error:
```
com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value`.
```

JSON requests some ascii characters such as `\n` and `\t` to be escaped. Could you add a mechanism to escape these characters as well?

**Comment by kyoshinaga** [comment]
Sorry for my inadequate modification. I'll add that escaping into the `JSONUtil.toJSONFromNode` asap.

**Comment by kyoshinaga** [comment]
I add the mechanism to escape special characters.
Test result is as follows:

- Input file: test.txt
```
Newline\n
Tab\t\n
Backslash\
```
Note: Each special character (e.g. `\n`) is ascii code in this file.

- Command

```bash
$ cat test.txt | java -cp "./target/jigg-assembly-0.6.2.jar" jigg.pipeline.Pipeline -annotators "ssplit" \
-ssplit.pattern "\." -outputFormat [xml|json]
```

- XML output
```xml
<?xml version='1.0' encoding='UTF-8'?>
<root>
  <document id="d0">
    <sentences>
      <sentence characterOffsetEnd="23" characterOffsetBegin="0" id="s0">Newline Tab Backslash\</sentence>
    </sentences>
  </document>
</root>
```

- JSON output
```json
{
  ".tag" : "root",
  ".child" : [ {
    ".tag" : "document",
    "id" : "d0",
    ".child" : [ {
      ".tag" : "sentences",
      ".child" : [ {
        ".tag" : "sentence",
        "text" : "Newline\nTab\t\nBackslash\\",
        "id" : "s0",
        "characterOffsetBegin" : "0",
        "characterOffsetEnd" : "23"
      } ]
    } ]
  } ]
}
```

Is this performance correct?

**Comment by hiroshinoji** [comment]
Looks good. Thank you.
