### ISSUE TITLE
Japanese model

### ISSUE THREAD

**Issue by sangtb92** [mynlp/jigg#98]
Hi, I am interested in use Jigg with Japanese.
Are you working on Japanese?
And how can I start building a Japanese model for NER?
Thanks!

**Comment by hiroshinoji** [comment]
Thank you for your interest. If your goal is Japanese NER, maybe the current choice is only using KNP, for which Jigg provides a wrapper with more readable format and parallel processing. Unfortunately currently we don't support JUMAN++, which provides superior results to JUMAN as a preprocess of KNP. We will add JUMAN++ to our TODO and will support it soon.

The basic command to have a pipeline with JUMAN and KNP is `-annotators "ssplit,juman,knp"`. Before calling, JUMAN and KNP should be installed on the machine and added to the path.

**Comment by sangtb92** [comment]
Thank you for your suggestion! 👍
